// Users
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const EDIT_MY_PROFILE_SUCCESS = 'EDIT_MY_PROFILE_SUCCESS';

// Roles
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const ADD_ROLE_SUCCESS = 'ADD_ROLE_SUCCESS';
export const EDIT_ROLE_SUCCESS = 'EDIT_ROLE_SUCCESS';

// Notifications
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const MARK_NOTIFICATION_AS_READ_SUCCESS =
	'MARK_NOTIFICATION_AS_READ_SUCCESS';
export const MARK_NOTIFICATION_AS_UNREAD_SUCCESS =
	'MARK_NOTIFICATION_AS_UNREAD_SUCCESS';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';

// Reservations
export const GET_CALENDAR_RESERVATIONS_SUCCESS =
	'GET_CALENDAR_RESERVATIONS_SUCCESS';
export const CREATE_AN_APPOINTMENT_SUCCESS = 'CREATE_AN_APPOINTMENT_SUCCESS';
export const GET_MY_APPOINTMENTS_SUCCESS = 'GET_MY_APPOINTMENTS_SUCCESS';
export const DELETE_MY_APPOINTMENT_SUCCESS = 'DELETE_MY_APPOINTMENT_SUCCESS';
